// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'https://christful-backend.vercel.app' | 'http://localhost:5000' | (string & {});
};

export type User = {
    id?: string;
    firstName?: string;
    lastName?: string;
    email?: string;
    bio?: string | null;
    avatarUrl?: string | null;
    googleId?: string | null;
    createdAt?: string;
    updatedAt?: string;
};

export type Post = {
    id?: string;
    content?: string | null;
    imageUrl?: string | null;
    videoUrl?: string | null;
    audioUrl?: string | null;
    mediaType?: 'text' | 'image' | 'video' | 'audio' | 'text_image' | 'text_video' | 'text_audio';
    userId?: string;
    author?: User;
    likes?: Array<{
        [key: string]: unknown;
    }>;
    comments?: Array<Comment>;
    createdAt?: string;
    updatedAt?: string;
};

export type Comment = {
    id?: string;
    content?: string;
    userId?: string;
    postId?: string;
    parentCommentId?: string | null;
    author?: User;
    likes?: Array<{
        [key: string]: unknown;
    }>;
    createdAt?: string;
    updatedAt?: string;
};

export type Community = {
    id?: string;
    name?: string;
    description?: string | null;
    avatarUrl?: string | null;
    coverUrl?: string | null;
    isPrivate?: boolean;
    createdBy?: string;
    creator?: User;
    memberships?: Array<Membership>;
    groups?: Array<Group>;
    createdAt?: string;
    updatedAt?: string;
};

export type Membership = {
    id?: string;
    userId?: string;
    communityId?: string;
    role?: 'member' | 'moderator' | 'admin';
    user?: User;
};

export type JoinRequest = {
    id?: string;
    userId?: string;
    communityId?: string;
    status?: 'pending' | 'approved' | 'rejected';
    user?: User;
};

export type Group = {
    id?: string;
    name?: string;
    description?: string | null;
    avatarUrl?: string | null;
    communityId?: string | null;
    createdBy?: string;
    inviteToken?: string | null;
    adminOnlyMessaging?: boolean;
    creator?: User;
    community?: {
        [key: string]: unknown;
    };
    members?: Array<GroupMember>;
    createdAt?: string;
    updatedAt?: string;
};

export type GroupMember = {
    id?: string;
    userId?: string;
    groupId?: string;
    role?: 'member' | 'admin';
    user?: User;
};

export type Message = {
    id?: string;
    content?: string | null;
    mediaType?: 'text' | 'image' | 'video' | 'audio' | 'text_image' | 'text_video' | 'text_audio';
    imageUrl?: string | null;
    videoUrl?: string | null;
    audioUrl?: string | null;
    userId?: string;
    groupChatId?: string;
    replyToMessageId?: string | null;
    sender?: User;
    replyToMessage?: Message;
    reactions?: Array<MessageReaction>;
    createdAt?: string;
    updatedAt?: string;
};

export type MessageReaction = {
    id?: string;
    messageId?: string;
    userId?: string;
    emoji?: string;
    user?: User;
};

export type Notification = {
    id?: string;
    userId?: string;
    type?: 'like' | 'comment' | 'follow' | 'join_community' | 'join_request' | 'join_approved' | 'join_rejected' | 'added_to_group' | 'user_joined_group';
    message?: string;
    relatedId?: string;
    isRead?: boolean;
    createdAt?: string;
    updatedAt?: string;
};

export type SavedPost = {
    id?: string;
    userId?: string;
    postId?: string;
    post?: Post;
    createdAt?: string;
    updatedAt?: string;
};

export type Error = {
    message?: string;
    error?: string;
};

export type GetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostRegisterData = {
    body: {
        firstName: string;
        lastName: string;
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/register';
};

export type PostRegisterErrors = {
    /**
     * Bad request (e.g. email exists)
     */
    400: Error;
};

export type PostRegisterError = PostRegisterErrors[keyof PostRegisterErrors];

export type PostRegisterResponses = {
    /**
     * User created
     */
    201: unknown;
};

export type PostLoginData = {
    body: {
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/login';
};

export type PostLoginErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * User not found
     */
    404: unknown;
};

export type PostLoginResponses = {
    /**
     * Login successful
     */
    200: unknown;
};

export type PostGoogleAuthData = {
    body: {
        access_token: string;
    };
    path?: never;
    query?: never;
    url: '/google-auth';
};

export type PostGoogleAuthResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PatchAuthMeData = {
    body?: {
        bio?: string;
        avatar?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type PatchAuthMeResponses = {
    /**
     * Success
     */
    200: {
        message?: string;
        user?: User;
    };
};

export type PatchAuthMeResponse = PatchAuthMeResponses[keyof PatchAuthMeResponses];

export type PostForgotPasswordData = {
    body: {
        email: string;
    };
    path?: never;
    query?: never;
    url: '/forgot-password';
};

export type PostForgotPasswordResponses = {
    /**
     * Success (message is generic for security)
     */
    200: unknown;
};

export type PostResetPasswordData = {
    body: {
        token: string;
        newPassword: string;
    };
    path?: never;
    query?: never;
    url: '/reset-password';
};

export type PostResetPasswordResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user';
};

export type GetUserResponses = {
    /**
     * Success
     */
    200: User;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type GetUsersResponses = {
    /**
     * Success
     */
    200: Array<User>;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type DeleteUsersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type DeleteUsersByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetUsersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type GetUsersByIdResponses = {
    /**
     * Success
     */
    200: User;
};

export type GetUsersByIdResponse = GetUsersByIdResponses[keyof GetUsersByIdResponses];

export type PutUsersByIdData = {
    body?: {
        firstName?: string;
        lastName?: string;
        email?: string;
        password?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type PutUsersByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/profile';
};

export type GetProfileResponses = {
    /**
     * Success
     */
    200: User;
};

export type GetProfileResponse = GetProfileResponses[keyof GetProfileResponses];

export type PostSendemailData = {
    body: {
        email: string;
    };
    path?: never;
    query?: never;
    url: '/sendemail';
};

export type PostSendemailResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetPostsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
    };
    url: '/posts';
};

export type GetPostsResponses = {
    /**
     * Success
     */
    200: {
        posts?: Array<Post>;
        total?: number;
        page?: number;
        totalPages?: number;
    };
};

export type GetPostsResponse = GetPostsResponses[keyof GetPostsResponses];

export type PostPostsData = {
    body?: {
        content?: string;
        image?: Blob | File;
        video?: Blob | File;
        audio?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/posts';
};

export type PostPostsResponses = {
    /**
     * Post created
     */
    201: {
        message?: string;
        post?: Post;
    };
};

export type PostPostsResponse = PostPostsResponses[keyof PostPostsResponses];

export type DeletePostsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/posts/{id}';
};

export type DeletePostsByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetPostsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/posts/{id}';
};

export type GetPostsByIdResponses = {
    /**
     * Success
     */
    200: Post;
};

export type GetPostsByIdResponse = GetPostsByIdResponses[keyof GetPostsByIdResponses];

export type PutPostsByIdData = {
    body?: {
        content?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/posts/{id}';
};

export type PutPostsByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostPostsByIdLikeData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/posts/{id}/like';
};

export type PostPostsByIdLikeResponses = {
    /**
     * Unliked
     */
    200: unknown;
    /**
     * Liked
     */
    201: unknown;
};

export type DeletePostsByIdSaveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/posts/{id}/save';
};

export type DeletePostsByIdSaveResponses = {
    /**
     * Post unsaved
     */
    200: unknown;
};

export type PostPostsByIdSaveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/posts/{id}/save';
};

export type PostPostsByIdSaveResponses = {
    /**
     * Post saved
     */
    201: unknown;
};

export type GetPostsSavedData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
    };
    url: '/posts/saved';
};

export type GetPostsSavedResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetPostsByIdSavedStatusData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/posts/{id}/saved-status';
};

export type GetPostsByIdSavedStatusResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostReelsData = {
    body?: {
        content?: string;
        video: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/reels';
};

export type PostReelsResponses = {
    /**
     * Reel created
     */
    201: unknown;
};

export type GetReelsSuggestedData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
    };
    url: '/reels/suggested';
};

export type GetReelsSuggestedResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetPostsByPostIdCommentsData = {
    body?: never;
    path: {
        postId: string;
    };
    query?: never;
    url: '/posts/{postId}/comments';
};

export type GetPostsByPostIdCommentsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostPostsByPostIdCommentsData = {
    body?: {
        content: string;
        parentCommentId?: string | null;
    };
    path: {
        postId: string;
    };
    query?: never;
    url: '/posts/{postId}/comments';
};

export type PostPostsByPostIdCommentsResponses = {
    /**
     * Comment created
     */
    201: unknown;
};

export type GetCommentsByCommentIdRepliesData = {
    body?: never;
    path: {
        commentId: string;
    };
    query?: never;
    url: '/comments/{commentId}/replies';
};

export type GetCommentsByCommentIdRepliesResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetCommentsByCommentIdThreadData = {
    body?: never;
    path: {
        commentId: string;
    };
    query?: never;
    url: '/comments/{commentId}/thread';
};

export type GetCommentsByCommentIdThreadResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type DeleteCommentsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/comments/{id}';
};

export type DeleteCommentsByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PutCommentsByIdData = {
    body?: {
        content?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/comments/{id}';
};

export type PutCommentsByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostCommentsByIdLikeData = {
    body?: {
        reactionType?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/comments/{id}/like';
};

export type PostCommentsByIdLikeResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetCommunitiesData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        search?: string;
    };
    url: '/communities';
};

export type GetCommunitiesResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostCommunitiesData = {
    body?: {
        name: string;
        description?: string;
        isPrivate?: boolean;
        avatar?: Blob | File;
        cover?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/communities';
};

export type PostCommunitiesResponses = {
    /**
     * Community created
     */
    201: unknown;
};

export type GetCommunitiesSearchData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        page?: number;
        limit?: number;
    };
    url: '/communities/search';
};

export type GetCommunitiesSearchResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetCommunitiesSuggestedData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
    };
    url: '/communities/suggested';
};

export type GetCommunitiesSuggestedResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type DeleteCommunitiesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/communities/{id}';
};

export type DeleteCommunitiesByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetCommunitiesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/communities/{id}';
};

export type GetCommunitiesByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PutCommunitiesByIdData = {
    body?: {
        name?: string;
        description?: string;
        isPrivate?: boolean;
        avatar?: Blob | File;
        cover?: Blob | File;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/communities/{id}';
};

export type PutCommunitiesByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostCommunitiesByIdJoinData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/communities/{id}/join';
};

export type PostCommunitiesByIdJoinResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostCommunitiesByIdLeaveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/communities/{id}/leave';
};

export type PostCommunitiesByIdLeaveResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostCommunitiesByIdRequestJoinData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/communities/{id}/request-join';
};

export type PostCommunitiesByIdRequestJoinResponses = {
    /**
     * Request sent
     */
    201: unknown;
};

export type GetCommunitiesByIdJoinRequestsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/communities/{id}/join-requests';
};

export type GetCommunitiesByIdJoinRequestsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostCommunitiesByCommunityIdJoinRequestsByRequestIdApproveData = {
    body?: never;
    path: {
        communityId: string;
        requestId: string;
    };
    query?: never;
    url: '/communities/{communityId}/join-requests/{requestId}/approve';
};

export type PostCommunitiesByCommunityIdJoinRequestsByRequestIdApproveResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostCommunitiesByCommunityIdJoinRequestsByRequestIdRejectData = {
    body?: never;
    path: {
        communityId: string;
        requestId: string;
    };
    query?: never;
    url: '/communities/{communityId}/join-requests/{requestId}/reject';
};

export type PostCommunitiesByCommunityIdJoinRequestsByRequestIdRejectResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type DeleteCommunitiesByCommunityIdMembersByUserIdData = {
    body?: never;
    path: {
        communityId: string;
        userId: string;
    };
    query?: never;
    url: '/communities/{communityId}/members/{userId}';
};

export type DeleteCommunitiesByCommunityIdMembersByUserIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PatchCommunitiesByCommunityIdMembersByUserIdRoleData = {
    body?: {
        role: 'member' | 'moderator' | 'admin';
    };
    path: {
        communityId: string;
        userId: string;
    };
    query?: never;
    url: '/communities/{communityId}/members/{userId}/role';
};

export type PatchCommunitiesByCommunityIdMembersByUserIdRoleResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetGroupsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/groups';
};

export type GetGroupsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostGroupsData = {
    body?: {
        name: string;
        description?: string;
        avatar?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/groups';
};

export type PostGroupsResponses = {
    /**
     * Group created
     */
    201: unknown;
};

export type GetCommunitiesByCommunityIdGroupsData = {
    body?: never;
    path: {
        communityId: string;
    };
    query?: never;
    url: '/communities/{communityId}/groups';
};

export type GetCommunitiesByCommunityIdGroupsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostCommunitiesByCommunityIdGroupsData = {
    body?: {
        name: string;
        description?: string;
    };
    path: {
        communityId: string;
    };
    query?: never;
    url: '/communities/{communityId}/groups';
};

export type PostCommunitiesByCommunityIdGroupsResponses = {
    /**
     * Group created
     */
    201: unknown;
};

export type DeleteCommunitiesByCommunityIdGroupsByGroupIdData = {
    body?: never;
    path: {
        communityId: string;
        groupId: string;
    };
    query?: never;
    url: '/communities/{communityId}/groups/{groupId}';
};

export type DeleteCommunitiesByCommunityIdGroupsByGroupIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PutCommunitiesByCommunityIdGroupsByGroupIdData = {
    body?: {
        name?: string;
        description?: string;
    };
    path: {
        communityId: string;
        groupId: string;
    };
    query?: never;
    url: '/communities/{communityId}/groups/{groupId}';
};

export type PutCommunitiesByCommunityIdGroupsByGroupIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type DeleteGroupsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/groups/{id}';
};

export type DeleteGroupsByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetGroupsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/groups/{id}';
};

export type GetGroupsByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PutGroupsByIdData = {
    body?: {
        name?: string;
        description?: string;
        avatar?: Blob | File;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/groups/{id}';
};

export type PutGroupsByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostGroupsByGroupIdMembersData = {
    body?: {
        userId: string;
    };
    path: {
        groupId: string;
    };
    query?: never;
    url: '/groups/{groupId}/members';
};

export type PostGroupsByGroupIdMembersResponses = {
    /**
     * Success
     */
    201: unknown;
};

export type DeleteGroupsByGroupIdMembersByMemberIdData = {
    body?: never;
    path: {
        groupId: string;
        memberId: string;
    };
    query?: never;
    url: '/groups/{groupId}/members/{memberId}';
};

export type DeleteGroupsByGroupIdMembersByMemberIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PatchGroupsByGroupIdMembersByMemberIdData = {
    body?: {
        role: 'member' | 'admin';
    };
    path: {
        groupId: string;
        memberId: string;
    };
    query?: never;
    url: '/groups/{groupId}/members/{memberId}';
};

export type PatchGroupsByGroupIdMembersByMemberIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostGroupsByGroupIdLeaveData = {
    body?: never;
    path: {
        groupId: string;
    };
    query?: never;
    url: '/groups/{groupId}/leave';
};

export type PostGroupsByGroupIdLeaveResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostGroupsByGroupIdInviteLinkData = {
    body?: never;
    path: {
        groupId: string;
    };
    query?: never;
    url: '/groups/{groupId}/invite-link';
};

export type PostGroupsByGroupIdInviteLinkResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostGroupsJoinViaLinkData = {
    body?: {
        inviteToken: string;
    };
    path?: never;
    query?: never;
    url: '/groups/join-via-link';
};

export type PostGroupsJoinViaLinkResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PatchGroupsByGroupIdSettingsAdminOnlyMessagingData = {
    body?: {
        adminOnlyMessaging?: boolean;
    };
    path: {
        groupId: string;
    };
    query?: never;
    url: '/groups/{groupId}/settings/admin-only-messaging';
};

export type PatchGroupsByGroupIdSettingsAdminOnlyMessagingResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type DeleteUsersByUserIdFollowData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/users/{userId}/follow';
};

export type DeleteUsersByUserIdFollowResponses = {
    /**
     * Unfollowed
     */
    200: unknown;
};

export type PostUsersByUserIdFollowData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/users/{userId}/follow';
};

export type PostUsersByUserIdFollowResponses = {
    /**
     * Followed
     */
    201: unknown;
};

export type GetUsersByUserIdFollowersData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/users/{userId}/followers';
};

export type GetUsersByUserIdFollowersResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetUsersByUserIdFollowingData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/users/{userId}/following';
};

export type GetUsersByUserIdFollowingResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetUsersByUserIdFollowStatusData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/users/{userId}/follow-status';
};

export type GetUsersByUserIdFollowStatusResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetGroupsByGroupIdMessagesData = {
    body?: never;
    path: {
        groupId: string;
    };
    query?: {
        page?: number;
        limit?: number;
    };
    url: '/groups/{groupId}/messages';
};

export type GetGroupsByGroupIdMessagesResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostGroupsByGroupIdMessagesData = {
    body?: {
        content?: string;
        replyToMessageId?: string;
        image?: Blob | File;
        video?: Blob | File;
        audio?: Blob | File;
    };
    path: {
        groupId: string;
    };
    query?: never;
    url: '/groups/{groupId}/messages';
};

export type PostGroupsByGroupIdMessagesResponses = {
    /**
     * Message sent
     */
    201: unknown;
};

export type GetGroupChatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/group-chats';
};

export type GetGroupChatsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type DeleteMessagesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/messages/{id}';
};

export type DeleteMessagesByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PutMessagesByIdData = {
    body?: {
        content?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/messages/{id}';
};

export type PutMessagesByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type DeleteMessagesByIdReactData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/messages/{id}/react';
};

export type DeleteMessagesByIdReactResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostMessagesByIdReactData = {
    body?: {
        emoji?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/messages/{id}/react';
};

export type PostMessagesByIdReactResponses = {
    /**
     * Success
     */
    201: unknown;
};

export type GetNotificationsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        unreadOnly?: 'true' | 'false';
    };
    url: '/notifications';
};

export type GetNotificationsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PatchNotificationsByIdReadData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/notifications/{id}/read';
};

export type PatchNotificationsByIdReadResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PatchNotificationsReadAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifications/read-all';
};

export type PatchNotificationsReadAllResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type DeleteNotificationsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/notifications/{id}';
};

export type DeleteNotificationsByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};
